apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv-claim
  labels:
    type: vprodb
spec:
  storageClassName: default
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
